### ISSUE TITLE
TRANSFORM_ARGUMENT functions are executed after PQs

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#100]

**Comment by kbrandwijk** [comment]
Documentation on event hooks says transform_argument fires before permission API.

**Steps to reproduce:**
- Create a Type with an integer field
- Create a node with that field set to **1**
- Create a transform_argument event hook on update that sets that field to, for example **5**
- Create a PQ on update that checks if that field equals **5**
- Create an update mutation that sets the field to **3**

**Expected behavior**: transform_argument fires first, changing the value to 5, after that, PQ should pass.
**Actual behavior**: PQ fails

**Conclusion**: PQ fires first...

**Comment by marktani** [comment]
Can you show the exact PQ you use? I'm afraid it does not do what you expect.

**Comment by kbrandwijk** [comment]
It seems like you entirely skipped the part about transform_argument. What you're showing, is just the permission query.

**Comment by marktani** [comment]
With the permission query I'm using, the `TRANSFORM_ARGUMENT` function I used does not affect the outcome of the PQ, so I skipped it in my descriptions above:

```js
module.exports = function (event) {
  event.data.int = 3
  return {data: event.data}
}
```

That's because the `TRANSFORM_ARGUMENT` function affects the input arguments and not the node data itself, while the PQ runs against the node data itself.

Do your PQ or function differ notably from mine?

**Comment by kbrandwijk** [comment]
If you set the int field to '3' in the transform_argument, and then check for '3' in your PQ, that should always pass, right?

**Comment by marktani** [comment]
No - the PQ above checks the following conditions:

> does the node that is being updated have the value `int: 3`?

and not:

> is the node about to be updated so that it has the value `int: 3`.

**Comment by kbrandwijk** [comment]
I see the difference now. My PQ used $input_int. Which value should that have according to you?

**Comment by marktani** [comment]
Was that the only difference you had? 🙂 Then your PQ would say

> Only allow the node to be updated if the input and the current data for `int` is the same

If you want to enforce something like

> Only allow the update mutation if the input value for `int` is 3

then you could check that in the function itself. Right now, PQ do not cover this use case easily (there's a weird workaround: create a type with an integer field, create a node with the value 3 and check if the input equals that node's integer value 🙂)

**Comment by kbrandwijk** [comment]
My point was, that the $input_int field of the PQ has the value of the original mutation, not the value that was updated in the function hook. That means the PQ runs on untransformed data, even though the docs state that PQ run _after_ the event hooks.

**Comment by marktani** [comment]
Got it!

**Comment by marktani** [comment]
I could verify your assumption. PQ:

```graphql
query ($node_id: ID!, $input_int: Int!) {
  SomePostExists(
    filter:  {
      id: $node_id
      int: $input_int
    }
  )
}
```

`TRANSFORM_ARGUMENT` for `Post is updated`:

```js
module.exports = function (event) {
  event.data.int = 3
  return {data: event.data}
}
```

Mutations:

```graphql
mutation create {
  createPost(int: 2) {
    id
    int
  }
}

mutation works {
  updatePost(id: "ID_FROM_ABOVE" int: 3) {
    id
    int
  }
}

mutation doesntwork {
  updatePost(id: "ID_FROM_ABOVE" int: 2) {
    id
    int
  }
}
```

Mutation `doesntwork` should work, but doesn't 😛 
Thanks so much for bearing with me and bringing this up! 🙌

**Comment by kbrandwijk** [comment]
No problem, glad we got it sorted out now!

**Comment by kbrandwijk** [comment]
Is this actually a bug, or desired functionality? When are PQ's supposed to run, before all RP, after transform_argument, before pre_write, after pre_write.

It's quite hard to determine how to proceed with this. The Console says `PRE_WRITE` is useful for calling external services like _charge a customer on stripe_. For stuff likes that, it makes a _big_ difference to know when the PQ is supposed to run. E.g. I'm not charging a customer before the PQ runs...
