### ISSUE TITLE
Different HTTP status code for File and Image API for file not found

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#101]
The Image API returns 502 Bad gateway when you try to request an image that does (no longer) exist. 
The File API returns 403 Forbidden when a file does (no longer) exist.

Please return a 404 in both cases.

**Comment by marktani** [comment]
The issue with the Image API is tracked [here](https://github.com/graphcool/serverless-image-proxy/issues/5).

We should fix the File API to return 404 instead 👍
