### ISSUE TITLE
Files not deleted right away when deleting in console or using deleteFile mutation

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#102]
Both ways of deleting a file (console and mutation) do not actually delete the file. It can still be retrieved from the existing URL. Deleting a file should really delete the file. I couldn't be bothered to fill my own 10GB limit to try, but for customers who get billed seperately for storage, this might also be an issue.

**Comment by kbrandwijk** [comment]
Update: apparently it took a few hours... Still worth looking at a way to invalidate the cache immediately

**Comment by marktani** [comment]
We currently cache files for an hour. In the future, we also want to allow [fast invalidation](https://github.com/graphcool/feature-requests/issues/254). Further discussions can be done in the FR 🙂
