### ISSUE TITLE
changing system or relation field with project migration has confusing error message

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/api-bugs#104]
When making changes directly to the schema, some changes are not handled correctly:

- Changing the name of a system field. When changing the name of a system field, you can preview, and apply changes. No error message is shown and the change is not applied.

- Changing the name of a relation field. Throws an error, but with a confusing message: "You can only create scalar fields and 'Post' is not a scalar value. Did you intend to create a relation?". I'm not creating a field, or a relation, I'm just renaming the field.

Thanks @kbrandwijk for reporting this!

**Comment by marktani** [comment]
Long-term, we want to move away from the `createdAt` and `updatedAt` fields, so this is likely not being addressed before.

The other bug can be tracked here: #91.
