### ISSUE TITLE
project migration asks for migrationValue when it doesn't need to

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/api-bugs#105]
- If no nodes exists for a Type, and you **change** a field to required using the schema editor, that change applies correctly.

- If nodes exists for a Type, the schema editor **always** asks for a migration value, even though all nodes have a value in that field.

- If you change a field from required to not required, the editor also asks for a migration value, which is incorrect.

- If you change the field type, the editor **always** asks for a migration value, even if the change would not cause any data loss (like: from Int to String). This one is the worst, because in this case, the migration value is **always** applied to every node, causing data loss!

Please improve the check to only require a migrationvalue for new, required fields on Types with existing nodes, and on changing a field **to** required if there are nodes with null values in that field.

Bonus feature request: add the '@migrationValue' attribute automatically, just like the '@rename' is added automatically when you change the name of a field.

Moved here from https://github.com/graphcool/console/issues/1080
Thanks @kbrandwijk for reporting

**Comment by kbrandwijk** [comment]
This one has just become worse, because the migration value can only be entered when a warning is visible...
![annoying](https://user-images.githubusercontent.com/852069/27990095-013a3032-644c-11e7-9152-ebabcce1a9e0.gif)

**Comment by marktani** [comment]
This should be fixed 🙂
