### ISSUE TITLE
Add filter descriptions in the GraphQL schema

### ISSUE THREAD

**Issue by artyomchel** [graphcool/api-bugs#108]
So that people know what the filters actually do without having to randomly try it, especially since currently we also don't have an FAQ/article on this.

**Comment by dpetrick** [comment]
Verify and close please.

**Comment by artyomchel** [comment]
How do I do this now?

**Comment by dpetrick** [comment]
Apologies, the fix is not live yet. I will verify it once it is.

**Comment by dpetrick** [comment]
Verified - descriptions are added.
