### ISSUE TITLE
Cloning a project references same files

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#109]
> If you copy a project including data, the files are not copied. The file secrets are the same in both projects. Not specific to cli though, same thing happens on clone project in console.

**Comment by marktani** [comment]
We will tackle this when improving the clone project feature in general. You will be able to either reference the same files, or not copy them over at all. Let's continue the discussion here: https://github.com/graphcool/feature-requests/issues/255

**Comment by kbrandwijk** [comment]
Well, this one is a bit too serious to move from bug to feature request imho. Why? Because you can actually loose data because of this!

**Comment by marktani** [comment]
Actually, I just noticed that you can clone without copying the data and it will not copy the file nodes either. It's not 💯 intuitive, but it's actually behaving correctly.

**Comment by kbrandwijk** [comment]
Yes, cloning a project _without_ data behaves correctly. That was, however, not part of this issue. If I clone a project, I expect to have two completely independent projects. If you want to improve clone functionality in general, great. But anything that can cause data loss, is a bug.
