### ISSUE TITLE
API does not respond to Accept-encoding: gzip header

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#110]
The API does not gzip responses, even if Accept-encoding: gzip header is present. For mobile app purposes, or other low bandwidth situations, gzipping responses would really help saving bandwidth.
It's not advised to do it by default, because it slightly increases latency. Adhering to the Accept-encoding header lets the user make the decision..

**Comment by kbrandwijk** [comment]
Any progress on this?

**Comment by marktani** [comment]
Unfortunately not yet 🙂
