### ISSUE TITLE
Anonymous authentication field 'secret' is not a system field

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#112]
It's not a system field, because you have to be able to enter the secret, and that's not possible if it's a system field.

But because it is not a system field, you can rename it, change type, etc., and that will break the authenticate mutation.

Proposal: make it a system field, and create a seperate mutation registerAnonymousSecret or something like that to set the value of the field.

**Comment by marktani** [comment]
This is part of a bigger topic that can be discussed here: https://github.com/graphcool/feature-requests/issues/252

There should be an overview of the current state of a project, so in this case you should see that the  `secret` field is not correctly setup.
