### ISSUE TITLE
Only first defined event hook fires

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#113]
If you define more than one hook for the same event, only the first one created fires.
If the functions are inline, you could of course combine them, but if either or both is an existing webhook, you can't.

Related to https://github.com/graphcool/feature-requests/issues/243

**Comment by marktani** [comment]
This is a [known limitation](https://www.graph.cool/docs/reference/functions/request-pipeline/overview-pa6guruhaf/#hook-points):

> For a given trigger, only **one function** can be assigned to each hook point.


 Let's further discuss in the feature request you posted.
