### ISSUE TITLE
GraphQL-up doesn't work from webpage

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#115]
**What is the current behavior?**
Creating a new graphql-up endpoint on the website doesn't show the correct types.
Also, the endpoint is not created correctly.

**If the current behavior is a bug, please provide the steps to reproduce it.**
- Click the example graphql-up button on https://www.graph.cool/graphql-up/
- See the imported schema representation on https://www.graph.cool/graphql-up/new/?source=https://graphqlbin.com/twitter.graphql
- It doesn't show you the types from the .graphql file
- Open the playground after creating the API
- Perform the introspection query
- The types from the .graphql file are indeed *not* created

**What is the expected behavior?**
Work as described: show types imported from .graphql on webpage, and actually create an endpoint with that schema behind it.

**Comment by marktani** [comment]
Thanks for bringing this up, it's now fixed 🙂
