### ISSUE TITLE
Custom headers not being considered for SSS webhooks

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#116]
**What is the current behavior?**

Setting a custom header/value for SSS functions does not affect the actual HTTP POST request. 

**If the current behavior is a bug, please provide the steps to reproduce it.**

Create a new SSS with webhook URL for https://requestb.in/. Set a custom header/value like `abc/abc`. Inspect the system API call that correctly contains the custom header. Then trigger the SSS and inspect the HTTP request at https://requestb.in/.

**What is the expected behavior?**

The HTTP POST should contain the custom header.

**Comment by schickling** [comment]
➤ Johannes Schickling commented:

Test

**Comment by marktani** [comment]
This seems to also affect RP functions.

**Comment by marktani** [comment]
This problem is a frontend issue and further discussed [here](https://github.com/graphcool/console/issues/1247).
