### ISSUE TITLE
isomorphic fetch has a blank response.json()

### ISSUE THREAD

**Issue by kguller** [graphcool/api-bugs#117]
**What is the current behavior?**
When using a Request Pipeline Function on PRE_WRITE stage using an inline function I ran into issues using the isomorphic-fetch library.  I made a basic GET call to a test REST api that is fully tested.  I wrapped the fetch in a Promise as suggested and all of my event data was returned properly, but the response from fetch always returns an empty object.  response.text() and response.json() both return an empty object, however the status and statusText are correct with 200 and OK.

**What is the expected behavior?**
response.json() should return the json displayed in the Postman screenshot:
```
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

![image](https://user-images.githubusercontent.com/1985853/27094181-1be39a14-501e-11e7-93e9-3046bdefc8d0.png)

**If the current behavior is a bug, please provide the steps to reproduce it.**

Here is my source code screenshot and code.
![image](https://user-images.githubusercontent.com/1985853/27094378-bb670990-501e-11e7-96a8-33cd85a6be38.png)

EXAMPLE EVENT
```
{
  "data": {
    "createdAt": "2017-06-12T04:35:15.553Z",
    "id": "cj3tnaq5d00003i5wt45s4vg5",
    "request": {"method":"product.get"},
    "response": {},
    "updatedAt": "2017-06-12T04:35:15.553Z"
  },
  "context": {
    "headers": {}
  }
}
```

INLINE FUNCTION
```js
require('isomorphic-fetch');
module.exports = function (event) {
 
  var api = "http://jsonplaceholder.typicode.com/posts/1"

  return new Promise((resolve, reject) => {
    fetch(api, {
      method: 'get',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      }
    }).then((response) => {
      event.data.response = {"test":"tested", "json":response.json()}
      resolve(event)
    }).then((data) => {
      resolve({error: 'Could not finish mutation, because only movies exist.'})
    }).catch((error) => {
      console.log(error)
      resolve({error: 'Could not connect to API'})
    })
  })  
}
```

**Comment by dhruska** [comment]
I am having this issue as well, with both `isomorphic-fetch` and `node-fetch`.

**Comment by marktani** [comment]
I cannot say for sure what is happening here, but the extra Promise wrapper is not needed. This works:

```js
require('isomorphic-fetch');
module.exports = function (event) {
 
  var api = "http://jsonplaceholder.typicode.com/posts/1"
  
  return fetch(api, {
      method: 'get',
      headers: {
        'Content-Type': 'application/json; charset=utf-8'
      }
    }).then((response) => {
    	return response.json()
    }).then((data) => {
      console.log(data)
      return {error: 'Could not finish mutation, because only movies exist.'}
    }).catch((error) => {
      console.log(error)
      return {error: 'Could not connect to API'}
    }) 
}
```

Could you share your code, @dhruska?

**Comment by marktani** [comment]
Ah, interestingly, `response.json()` returns a promise, so that's probably related.

**Comment by dhruska** [comment]
@marktani Ha, yeah that was definitely the problem! My code is very similar to the snippet you posted - the following is working for me:

```
const fetch = require('isomorphic-fetch')

module.exports = function (event) {
  return fetch(API_URL)
    .then((response) => {
      return response.json()
    })
  	.then((response) => {
      console.log(response)
  	})
    .catch(err => console.log(err))
}
```
