### ISSUE TITLE
Websocket connection makes request with http protocol

### ISSUE THREAD

**Issue by nigeltiany** [graphcool/api-bugs#119]
The implementation below shows a lot of errors about insecure usage. The stack is Meteor with a vuejs front end. Some headers are also considered unsafe and therefore not set.
![vue apollo with graph cool errors](https://user-images.githubusercontent.com/8957192/27199228-3d2a035e-51e3-11e7-8b0a-7d0bc4d0cb53.png)

```javascript
import Vue from 'vue'
import { ApolloClient, createNetworkInterface } from 'apollo-client'
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws'
import WebSocket from 'ws'

import VueApollo from 'vue-apollo'

//subscriptions socket client
const wsClient = new SubscriptionClient('ws://subscriptions.graph.cool/v1/cj251930v1rs80126aaf5olpl',  {
    reconnect: true,
    connectionParams: {
    }
}, WebSocket);

const  networkInterface = createNetworkInterface({
    uri: 'https://api.graph.cool/simple/v1/cj251930v1rs80126aaf5olpl',
    transportBatching: true
}).use([
    {
        applyMiddleware(request,next) {
            if(!request.options.headers) {
                request.options.headers = {}
            }
            if(localStorage.getItem('user')) {
                request.options.headers.authorization = `Bearer ${JSON.parse(localStorage.getItem('user')).token}`
            }
            next()
        }
    }
]);

// Extend the network interface with the subscription client
const interfaceWithSubscriptions = addGraphQLSubscriptions(
    networkInterface,
    wsClient,
);

export const apolloClient = new ApolloClient({
    networkInterface: interfaceWithSubscriptions
});

// Install the vue plugin
Vue.use(VueApollo, {
    apolloClient
});

// Create the apollo client
export function createApolloClient (initialState) {
    return apolloClient
}
```

**Comment by marktani** [comment]
Hey, can you try using `wss://subscriptions.graph.cool/v1/cj251930v1rs80126aaf5olpl` instead?

**Comment by nigeltiany** [comment]
Tried that but no success. Used ```ws``` to see what was happening without the extra security

**Comment by marktani** [comment]
What's your version of `subscription-transport-ws`? This looks like a client problem and not an API problem to me.

**Comment by nigeltiany** [comment]
The version is ```subscription-transport-ws: 0.7.3``` and you are probably right. I'll just manage the socket connection myself as shown [here on the docs](https://www.graph.cool/docs/reference/simple-api/making-api-requests-koo4eevun4/#establish-connection)

**Comment by marktani** [comment]
Could you still try `0.7.2` first? 🙂 

As for the documentation, it has been written for `0.5.4`. Let's discuss this further here: https://github.com/graphcool/content/issues/175.
