### ISSUE TITLE
Create mutation requires at least one field

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#124]
**What is the current behavior?**
If you execute a create mutation, you are required to specify at least one field (although the value can be `null`)

**What is the expected behavior?**
If a Type does not have any required fields, it should be possible to create a new node without specifying any fields in the create mutation

**Comment by marktani** [comment]
Can you share your schema and mutation? In general 

> Create mutation requires at least one field

is not correct.

**Comment by kbrandwijk** [comment]
I just found out that if I remove the braces, it works.

This works:
``` 
mutation {
  createTestType
  {
    id
  }
}
``` 

This throws an error:
```
mutation {
  createTestType()
  {
    id
  }
}
```

So even though it's a bit annoying (when working with dynamically constructed mutations), there is a way to make it work...

**Comment by marktani** [comment]
This is a GraphQL thing:

```
{
  "error": "Syntax error while parsing GraphQL query. Invalid input \"mutation {\\n  createTest()\", expected OperationDefinition, FragmentDefinition or TypeSystemDefinition (line 1, column 1):\nmutation {\n^"
}
```

Not a lot we can do here, so I'm closing the issue 🙂
