### ISSUE TITLE
Anonymous Auth provider is not generating valid Relay mutation 

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#140]
**What is the current behavior?**

When attaching the anonymous auth provider to type `User`, the mutation `authenticateUser(secret: String!)` gets generated for the Simple and Relay API.

**What is the expected behavior?**

However, this is not a valid Relay mutation. It should be `authenticateUser(input: {secret: String!})` instead.

**Comment by sorenbs** [comment]
Are you sure this is still the case with relay modern?
If not - should we still cater to relay classic like this?
@nikolasburk - would love to get your opinion.

**Comment by nikolasburk** [comment]
I'm 98,5% sure it's not a hard requirement in Relay Modern any more that input args have to be wrapped in a single input object. So, I believe the mutation is valid.

**Comment by Hagbarth** [comment]
@sorenbs I'm experiencing this in relay modern, is there a workaround or setting I'm missing?

**Comment by Hagbarth** [comment]
Anyway found a workaround using [graphql-request](https://github.com/graphcool/graphql-request):

In my index.js I just do:

```javascript
const endpoint = __SIMPLE_API_ENDPOINT__
const authenticate = `mutation Authenticate(
  $input: String!
) {
  authenticateAnonymousUser(secret: $input) {
    token
    id
  }
}`

request(endpoint, authenticate, {
  input: // Get the secret from where you store it,
}).then(data => {
  // Save token and render the app
})
```

**Comment by sorenbs** [comment]
That's great @Hagbarth 

I haven't actually used Relay Modern yet, but this quote from the documentation leads me to believe that it should be possible:

 > The restrictions on mutation queries from Relay Classic are also removed: mutation queries are static, fields can be arbitrarily nested, and may use arbitrary arguments

https://facebook.github.io/relay/docs/new-in-relay-modern.html

**Comment by Hagbarth** [comment]
Oh god 🤦‍♀️ 

I've been running relay moders w. `compat: true` which enforces that it's compatible w. relay classic.

Removing that from config fixes this.

**Comment by marktani** [comment]
Awesome, thanks for the digging @Hagbarth! We encourage everyone to [migrate their Relay Classic apps to Relay Modern](https://www.graph.cool/docs/tutorials/migrating-to-relay-modern-eijooto4se/), so this is intended behaviour.
