### ISSUE TITLE
IsUnique attribute ignored when creating project from schema

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#144]
When a graphql schema includes a field with `@isUnique` attribute, that attribute is ignored when creating the project from schema using the cli. Given that the schema is passed through to the API 1-on-1 (as far as I can see), this is probably an API bug.

CLI issue here: https://github.com/graphcool/graphcool-cli/issues/112

**Comment by marktani** [comment]
Thanks for the report @kbrandwijk, this is now working as expected. 🎉
