### ISSUE TITLE
Other project changes increase schema version

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#148]
**What is the current behavior?**
When I create or update a function, the schema version is increased. Thus, `graphcool push` does not work anymore, without doing a `pull` first. This is not obvious, because as a user, I have not made any changes to the schema, so I expect `push` to work.

**What is the expected behavior?**
Project version is only increased when changes are made to the schema.

**Comment by marktani** [comment]
This is a known limitation for now. An improved concept will be introduced as part of [this feature request](https://github.com/graphcool/feature-requests/issues/213).
