### ISSUE TITLE
Wrong interaction with Auth0

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#150]
**What is the current behavior?**

Using Auth0, it's possible to create a user as `EVERYONE` even when the permission is set to `AUTHENTICATED`.

**What is the expected behavior?**

A permission error should be returned instead.

**Comment by marktani** [comment]
`createUser` can be called as an authenticated user, even when no permissions for this mutation are available. This is with the email/pw provider.

**Comment by CameronK** [comment]
When I try to create a user as `EVERYONE`, regardless of the permission setting, I receive the `Insufficient Permissions`  error; however, *the user is still created!*

**Comment by lewisblackwood** [comment]
hey @marktani 👋 what's the expected timeframe for a fix on this? Being unable to validate the `createUser` mutation means the permissions framework is quite insecure 😬

**Comment by marktani** [comment]
Hey @CameronK and @lewisblackwood thanks for chiming in!

Let me clarify that *this behaviour is intended when an authentication provider is enabled*. This mechanism was employed with the typical web app in mind, where user signup is available to everyone.

Clearly, this behaviour does not fit all applications. This is something we learned in general about our authentication provider concepts, which promted us to offer custom authentication using schema extensions.

So, if you need better control here, I'm happy to help you transition your current setup to the schema extensions approach.

I'm sorry for the poor communication surrounding this topic from my side, I should have cleared this confusion up way sooner. Please reach out to me in Slack to discuss the migration path, or if you have any other question 🙂
