### ISSUE TITLE
You can't collaborate on a project if you have a project with the same name yourself

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#151]
**What is the current behavior?**
It might be an edge case, but if you try to invite someone as a collaborator on one of your projects, and that user has a project with the same name, you can't invite that user. Happened when I tried to invite someone to have a look at the default 'Example Project'.

**What is the expected behavior?**
The limitation shouldn't be there. But maybe the list of projects should show the owner below it for projects you are collaborating on, so you can see the difference between your own projects, and those of someone else.

**Comment by marktani** [comment]
I migrated this to [a feature request](https://github.com/graphcool/feature-requests/issues/286).
