### ISSUE TITLE
Removing yourself as collaborator on a project throws an error

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#152]
**What is the current behavior?**
Open project settings for a project you are collaborating on. Remove yourself as collaborator. You get an error like this:
![image](https://user-images.githubusercontent.com/852069/27611965-b7ae1358-5b94-11e7-80e4-ef0343ac443a.png)
The screen stays active. Clicking on any of the menu items gives a blank screen. Only refreshing the page switches to another project, and the project is gone from your list.

**What is the expected behavior?**
You should be able to remove yourself as collaborator on a project, but it should be handled properly.

**Comment by marktani** [comment]
This is rather something that [needs to be fixed in the Console](https://github.com/graphcool/console/issues/784).
