### ISSUE TITLE
Nested mutation does not trigger TRANSFORM_PAYLOAD functions

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#154]
**What is the current behavior?**

Creating a node in a nested mutation does not trigger the `TRANSFORM_PAYLOAD` function on that event.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Setup 

```graphql
type Outer implements Node {
  id: ID! @isUnique
  createdAt: DateTime!
  inner: Inner @relation(name: "InnerOnOuter")
  updatedAt: DateTime!
}

type Inner implements Node {
  id: ID! @isUnique
  createdAt: DateTime!
  outer: Outer @relation(name: "InnerOnOuter")
  number: Int
  updatedAt: DateTime!
}
```

and this `TRANSFORM_PAYLOAD` function on `Inner is created`:

```js
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  console.log(event.data)
  return {data: event.data}
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Mutation `a` correctly triggers the `TRANSFORM_PAYLOAD` function, mutation `b` does not.

```graphql
mutation a {
  createInner {
    id
  }
}

mutation b {
  createOuter(
    inner: {
      number: 123
    }
  ) {
    id
  }
}
```

**What is the expected behavior?**

Mutation `b` triggers the `TRANSFORM_PAYLOAD` function.

**Comment by CameronK** [comment]
@marktani Any updates on a fix for this? Also, curious if this applies to one-to-many relations as well.

**Comment by marktani** [comment]
Hey @CameronK sorry for not responding earlier but this is actually intended as of now.

The reasoning behind this is that `TRANSFORM_PAYLOAD` is supposed to be used to transform the mutation payload - so in a nested mutation that behaviour is not well-defined, because the mutation payload is always bound to the outer mutation.

Of course, another use case for `TRANSFORM_PAYLOAD` is to initiate external workflows, or to interact with the Graphcool API after the creation of a node. I'd be curious to hear if your use cases for this could be covered by a SSS Function, too 🙂

**Comment by marktani** [comment]
Closing this because it's not a bug. I'm happy to discuss this further in [a feature request](https://github.com/graphcool/feature-requests) or [the Forum](https://graph.cool/forum/).
