### ISSUE TITLE
Internal server error when querying required relation nested _meta

### ISSUE THREAD

**Issue by adrianocola** [graphcool/api-bugs#155]
**What is the current behavior?**
Query return the message `internal server error` when querying required relation nested _meta

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
Given this schema:

```graphql
type Sale implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  store: Store! @relation(name: "SaleOnStore") #REQUIRED!
  updatedAt: DateTime!
}

type Staff implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  store: Store! @relation(name: "StoreOnStaff")
  updatedAt: DateTime!
}

type Store implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  sales: [Sale!]! @relation(name: "SaleOnStore")
  staffs: [Staff!]! @relation(name: "StoreOnStaff")
  updatedAt: DateTime!
}
```

Relations:
`One Store is related to many Staffs`
`Many Sales are related to one Store`

**If applicable, share the query, mutation or subscription for reproduction**
```graphql
query{
  allSales{
    store{
      _staffsMeta{
        count
      }
    }
  }
}
```

Results: 
```json
{
  "data": null,
  "errors": [
    {
      "message": "Whoops. Looks like an internal server error. Please contact us in Slack (https://slack.graph.cool) and send us your Request ID: cj4hb9tv306fh0197z9hnvjk7",
      "requestId": "cj4hb9tv306fh0197z9hnvjk7",
      "path": [
        "allSales",
        0,
        "store",
        "_staffsMeta"
      ],
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ]
    }
  ]
}
```

If I change the `Sale->Store` relation to optional, the query works!
```graphql
type Sale implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  store: Store @relation(name: "SaleOnStore") #OPTIONAL
  updatedAt: DateTime!
}
```

And if I don't query the `_meta` field, the query works (even with the required relation):
```graphql
# this works!
query{
  allSales{
    store{
      staffs{
        id
      }
    }
  }
}
```

**What is the expected behavior?**
A required relation configuration should't affect the query result or return an error! It should work the same as the optional relation configuration.

**Comment by marktani** [comment]
First of all, thanks for the detailed write up @adrianocola! To reproduce the issue, at least two nodes need to be connected. So by running this mutation:

```graphql
mutation {
  createSale(name: "Sale" store: {
    name: "Store"
  }) {
    id
  }
}
```

I can reproduce this issue with the query you mentioned. We'll take a look at this as soon as we can 🙂

**Comment by marktani** [comment]
Closing as special case of #157.
