### ISSUE TITLE
Using a GraphQL alias on mutations gives Permission Error if type has a Permission Query for READ

### ISSUE THREAD

**Issue by adrianocola** [graphcool/api-bugs#156]
**What is the current behavior?**
Labeling a delete mutation gives an error if the deleted Type have a read permission query. The item is deleted, but the server returns a permission error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Given this schema:
```graphql
type Test implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  updatedAt: DateTime!
}
```

This EVERYONE READ permission query:
```graphql
query ($node_id: ID!) {
  SomeTestExists(
    filter: {
      id: $node_id
    }
  )
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Create some data:
```graphql
mutation{
  createTest(name: "test"){
    id # USE THIS ID!
  }
}
```

Try to delete (**run query as `EVERYONE`**):
```graphql
mutation{
  someLabel: deleteTest(id: "<PREV_ID>"){
    id
  }
}
```

Error:
```graphql
{
  "data": {
    "someLabel": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "someLabel",
        "id"
      ],
      "code": 3008,
      "message": "Insufficient Permissions",
      "requestId": "cj4ikit1y0usr0153erl6p5fr"
    }
  ]
}
```

If I remove the label or the READ permission query, everything works fine.

**What is the expected behavior?**
Not return a permission error!

**Comment by marktani** [comment]
Thanks for the detailed report! I can reproduce this and it also at least affects create mutations as well.
