### ISSUE TITLE
Can't require modules with a slash in inline functions

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#170]
**What is the current behavior?**

Requiring a module like `require('core-js/fn/regexp/escape')` or `require('mandrill-api/mandrill')` doesn't work. The function can't be created.

**What is the expected behavior?**

The function should be created and the module resolved correctly.

**Comment by kbrandwijk** [comment]
Using `'use latest'` and the `import mandrill from 'mandrill-api/mandrill'` syntax, this works.
Using the `require(...)` syntax, it doesn't.

So for importing submodules, use the `import ... from ...` syntax only.

**Comment by kbrandwijk** [comment]
Is this still a bug, or just something that needs to be documented?
