### ISSUE TITLE
Using gamequery module in function gets error

### ISSUE THREAD

**Issue by Samuell1** [graphcool/api-bugs#171]
Hey, when i try to use module https://github.com/kurt-stolle/node-gamequery, its returning error

**Code:**
```
var gamequery = require('gamequery')

// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  console.log(gamequery)
  return {data: event.data}
}
```

**What is the current behavior?**
```
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Module._compile (/data/sandbox/lib/module.js:127:21)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at WebtaskModule.require (/data/sandbox/lib/module.js:101:19)
at require (/data/sandbox/lib/module.js:136:21)
at Object.<anonymous> (/data/io/7c3b42b204774caa88df2729a670e4d1/webtask.js:1:79)
at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)

```

**Comment by marktani** [comment]
This work now, thanks for the report @Samuell1!

**Comment by Samuell1** [comment]
Error is not showing but when i test it again `console.log` doesnt work

![obrazok](https://user-images.githubusercontent.com/3110002/28179021-f21bc238-6800-11e7-8889-6f262a1175d0.png)

**Comment by kbrandwijk** [comment]
This is due to the module itself. On the current node version, 'use strict' is required, but missing in the gamequery sources. This occurs on other modules too, and has to be fixed in `gamequery`. I have opened an issue there: https://github.com/kurt-stolle/node-gamequery/issues/27. There's nothing that can be done on the Graphcool side.

**Comment by marktani** [comment]
Thanks a lot for clearing this up! As there's nothing we can do here, I'm closing this issue.

**Comment by kbrandwijk** [comment]
**General notice**: I have seen an issue lately about requiring `node-gamequery`. I have forked this repo to check something out, and have received an **official takedown notice** from Github today. Apparently, the node-gamequery library is a copyright infringement of the original library: https://github.com/sonicsnes/node-gamedig. Please use this original library only, all node-gamequery forks will be taken down by Github.
