### ISSUE TITLE
Creating nested nodes within parent update gives an error if relation is required

### ISSUE THREAD

**Issue by adrianocola** [graphcool/api-bugs#172]
**What is the current behavior?**
When updating a node and, in the same request, creating a nested 1xN relation, if the relation between the too is marked as required, the mutation gives an error. This used to work.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Schema:
```graphql
type Store implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  sales: [Sale!]! @relation(name: "SaleOnStore")
  updatedAt: DateTime!
}

type Sale implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  store: Store! @relation(name: "SaleOnStore")
  updatedAt: DateTime!
}
```

Note: relation between Sale an Store is required!

**If applicable, share the query, mutation or subscription for reproduction**

Create a `store`:
```graphql
mutation{
  createStore(
    name: "STORE1",
  ){
    id # save the returned ID
  }
}
```

Try to update the created store and create some sales in the same request:
```graphql
# This used to work, but now gives an error!
mutation{
  updateStore(
    id: "<previous_id>"
    sales: [
      {
        name: "SALE1"
      }
    ]
  ){
    id
  }
}
```

Error:
```graphql
{
  "data": {
    "updateStore": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateStore"
      ],
      "code": 3032,
      "message": "The field 'store' on type 'Sale' is required. Performing this mutation would violate the constraint",
      "requestId": "cj4udtlvf6yro0199hj29h7wt"
    }
  ]
}
```

Creating the store with the sales, doesn't gives an error:
```graphql
# This works!!!
mutation{
  createStore(
    name: "STORE1",
    sales: [
      {
        name: "SALE1"
      }
    ]
  ){
    id
  }
}
```

And if the relation is optional, the update don't gives an error

**What is the expected behavior?**
To create new nested nodes when the relation is required, as worked before.

**Comment by marktani** [comment]
This is actually intended behaviour. Let me elaborate!

* The first time you run the `updateStore` mutation, no error is returned - all good! A new sale is being created (let's call it  `SALE 1`) and connected to `STORE1`.
* The second time you run the `updateStore` mutation, let's say to add `STORE2`, this is what would happen:
  * First, `SALE1` would be disconnected from `STORE1`
  * Then, `SALE2` would be connected to `STORE1`

However, the first step is not allowed, because the relation is required. `SALE1` would end up without a connected store which would break this required constraint. Does this make sense?

**Comment by adrianocola** [comment]
It does! Maybe that error message was misleading. I thought that it was about the created nodes, not the nodes that would be disconnected.

You can close the issue or delete it!

**Comment by marktani** [comment]
Great, thanks for your confirmation! Once [nested updates](https://github.com/graphcool/feature-requests/issues/127) are implemented, this situation can be treated better 🙂
