### ISSUE TITLE
Can't add a many-to-many relation to types with data using schema migrations

### ISSUE THREAD

**Issue by j4mesjung** [graphcool/api-bugs#178]
I have two Nodes
type Card
type Deck

I want something that looks similar to this
```
Deck
{
  main: [Card],
  side: [Card]
}
```

Therefore, I add the relations like so:
```
type Card implements Node {
  main: [Deck!]! @relation(name: "MainDeckOnCard")
  side: [Deck!]! @relation(name: "SideDeckOnCard")
}
type Deck implements Node {
  main: [Card!]! @relation(name: "MainDeckOnCard")
  side: [Card!]! @relation(name: "SideDeckOnCard")
}
```

when I try to apply changes I receive this message
"You are adding a required relation to 'Card' but there are already items."

not sure what this means but figured this would work?

**Comment by j4mesjung** [comment]
I was able to add the field using the wizard by clicking 'Add Relation' under Deck.  However, I still get the same message when I try to change the relation name.  My schema now looks like this:
```
type Card implements Node {
  main: [Deck!]! @relation(name: "DeckOnCard")
  side: [Deck!]! @relation(name: "DeckOnCard1")
}
type Deck implements Node {
  main: [Card!]! @relation(name: "DeckOnCard")
  side: [Card!]! @relation(name: "DeckOnCard1")
}
```

**Comment by marktani** [comment]
Thanks for the report @j4mesjung! We'll fix this as soon as possible 🙂

**Comment by marktani** [comment]
This is now fixed :tada:
