### ISSUE TITLE
Referencing in mutation to not existing node throw error, despite this node is created

### ISSUE THREAD

**Issue by jakub-gawlas** [graphcool/api-bugs#18]
Hi ✋ 

Example schema (from `graphql-up` docu):
```graphql
type Tweet {
  id: ID!
  text: String!
  author: User! @relation(name: "Tweets")
}

type User {
  id: ID!
  name: String!
  tweets: [Tweet!]! @relation(name: "Tweets")
}
```

To mutation which create `Tweet` passed ID of not existing `User`:
```graphql
mutation {
  createTweet(text: "lorem ipsum", authorId: "iamfakeid") {
    id
  }
}
```
in response I get:
```
  "data": {
    "createTweet": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createTweet"
      ],
      "code": 3011,
      "message": "You are referencing a node that does not exist. Please check your mutation to make sure you are only creating edges between existing nodes.",
      "requestId": "cj0balm3axs2t01246v76w48f"
    }
  ]
}
```
Unfortunately new `Tweet` is created, although shouldn't be.

**Comment by marktani** [comment]
Hey, thanks for the report!

> Unfortunately new Tweet is created, although shouldn't be.

I'm actually not sure here. But it should be changed to either

* create the node, return the node in the response and throw the error, or
* don't create the node and return the error

**Comment by schickling** [comment]
➤ Nilan Marktanner commented:

Further discussion is continued in #12.
