### ISSUE TITLE
Can't require jwks-rsa 

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#181]
**What is the current behavior?**

Bug.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Try this function:

<img width="818" alt="screen shot 2017-07-12 at 20 42 25" src="https://user-images.githubusercontent.com/1780597/28134380-163b9c92-6743-11e7-8643-9ffe91b7cb79.png">

```js
const a = require('jwsk-rsa')

module.exports = function (event) {
  console.log(a)
  return {} 
}
```

It logs `undefined` instead of [the real module](https://github.com/auth0/node-jwks-rsa)

**What is the expected behavior?**

`const a = require('jwsk-rsa')` loads the real module.

**Comment by kbrandwijk** [comment]
![image](https://user-images.githubusercontent.com/852069/28134952-f1fe084a-6744-11e7-8283-23b7a0a98b9d.png)

**Comment by kbrandwijk** [comment]
This is because the module doesn't return an instance, this works as expected:
```
const jwksClient = require('jwks-rsa');

const client = jwksClient({
  strictSsl: true, // Default value
  jwksUri: 'https://sandrino.auth0.com/.well-known/jwks.json'
});


module.exports = function (event) {
  console.log(client)
  return {data: event.data}
}
```

**Comment by marktani** [comment]
Thanks @kbrandwijk 🙌
