### ISSUE TITLE
It's not possible to use migrationValue for int lists

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#184]
**What is the current behavior?**

`@migrationValue` is not applied for `[Int!]!` list fields. This probably also applies to other list types.

**Reproduction**

Given this schema

```graphql
type Post implements Node {
  id: ID! @isUnique
  ints: [Int!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

create a new post:

```graphql
mutation {
  createPost(ints: [1]) {
    id
  }
}
```

Then, neither of the following uses of `@migrationValue` will affect the value of `ints` for that post:

```graphql
type Post implements Node {
  id: ID! @isUnique
  ints: [Int!]! @migrationValue(value: "[]")
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

```graphql
type Post implements Node {
  id: ID! @isUnique
  ints: [Int!]! @migrationValue(value: "[1]")
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

```graphql
type Post implements Node {
  id: ID! @isUnique
  ints: [Int!]! @migrationValue(value: "[1, 2]")
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

The `preview changes` view is correct, and `applying changes` does not result into any error. But the change is not applied.

**What is the expected behavior?**

The migration value is applied correctly.

**Comment by valentinilk** [comment]
Similar behavior with Enums. Adding `tags: [MyEnum!]! @migrationValue(value: "[]")` to an existing type is not possible.
On the top right hand corner the following error appears, when trying to apply the changes: "The specified migration value is not a valid Enum Value for this field"

**Comment by marktani** [comment]
This is now fixed 💚
