### ISSUE TITLE
API supports only subset of ISO 8601 date standard

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#185]
**What is the current behavior?**
According to https://www.graph.cool/docs/faq/managing-date-and-time-in-graphql-ier7sa3eep/#the-iso-8601-format, Graphcool supports the ISO8601 format. However, a number of formats from that standard are not supported, more specifically the basic formatting, like:
- YYYYWwwD
- 20170714T154009Z (YYYYMMDDThhmmssZ)

**What is the expected behavior?**
This is either a documentation issue, or an API issue. If the API should support ISO8601, it should support th entire standard, instead of a subset. Or it should be clear from the documentation which limitations apply.

**Comment by marktani** [comment]
Thanks, I moved the issue to the [documentation](https://github.com/graphcool/content/issues/223).
