### ISSUE TITLE
Scalar node variable is not available in permission query

### ISSUE THREAD

**Issue by cj** [graphcool/api-bugs#188]
**What is the current behavior?**

When you select a scalar value and set your permission as follows:

![](https://image.prntscr.com/image/34HO_KuETJ6Iaxr5ziQrRQ.png)

When you save and open the permission again, it now looks like this:

![](https://image.prntscr.com/image/hX9cUf-PQvS8VqfdJv7sZQ.png)

**What is the expected behavior?**

For it to save the permission without removing the entire query tag.

**Comment by marktani** [comment]
How does the User type look like in the schema?

**Comment by cj** [comment]
@marktani here's my schema https://clips.twitch.tv/PhilanthropicDeliciousPlumAMPEnergyCherry

**Comment by marktani** [comment]
That might have been the wrong paste @cj 🤔

**Comment by cj** [comment]
@marktani indeed it was lol, I updated it to the correct one :)

**Comment by marktani** [comment]
Thanks! Will look into reproduction soon.

**Comment by vmatacale** [comment]
I reproduced this bug. It appears to be in the UI only. After the query is created with a scaler, if you open the query back up in the editor, the variables don't seem to be parsed correctly so the scaler fields aren't set properly. This triggers the validation.

All you have to do is click the correct scaler inputs and validation is passed again. It looks like the query is saved and works properly, it just loads improperly so it fails validation on an edit
