### ISSUE TITLE
Create mutation does not respect read permissions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#189]
**What is the current behavior?**
Create mutation returns fields that I am not allowed to read based on `READ` permission setup

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```
type Move implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  position: Int!
  result: ResponseStatus
  updatedAt: DateTime!
}
```
Permission: `CREATE` permission on `position` field
Permission: `READ` permission on `result` field

**If applicable, share the query, mutation or subscription for reproduction**
```
mutation{
  createMove(position: 1) {
    id
    position
    result
  }
}
```
Result:
```
{
  "data": {
    "createMove": {
      "id": "cj56ti2jprbsf0100vfizbks2",
      "position": 1,
      "result": "OK"
    }
  }
}
```

**What is the expected behavior?**
Insufficient permissions, because I am not allowed to read the `Id` and `position` fields.

**Comment by marktani** [comment]
I assume you're using an RP function to  populate the `result` field. What hook point does this function have?

**Comment by kbrandwijk** [comment]
`TRANSFORM_PAYLOAD`

**Comment by marktani** [comment]
This is intended behaviour and independent from your function setup. I added a note to the documentation: https://www.graph.cool/docs/reference/auth/important-notes-aej3ne1eez/

**Comment by kbrandwijk** [comment]
This is very inconsistent, and closes the door to a lot of use cases. The only workaround now is to create another Type to store this information in, because those permissions are respected. This will complicate the RP hooks tremendously.

**Comment by marktani** [comment]
I fully agree! We definitely have to rethink this behaviour, especially around the interaction with RP functions. We'll tackle this together with other unintuitive behaviour, for example that [type permissions are not registered when the mutation only contains related fields](https://github.com/graphcool/feature-requests/issues/245)
