### ISSUE TITLE
No permission check on empty result set

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#192]
**What is the current behavior?**
When querying a Type that has no nodes (or a filter has no results), an empty array is returned, even if the user has no `READ` permissions. From a pentest perspective, knowing there are no nodes is also a security leak (not for most Types, but for some use cases, especially with filters).
This is probably a big one to change, as current permission checking is on a per-node basis.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
First query:
```
query
{
  allUsers{ id }
}
```
Throws: insufficient permissions, so I know nothing

Second query:
```
query
{
  allUsers(filter:{ secret_starts_with: "a"}){ id}
}
```
Gives:
```
{
  "data": {
    "allUsers": []
  }
}
```
So I now know there are no users with a secret starting with 'a'. I could continue this line of querying to find by elimination (for example, if secret="c", and I get an empty array for a,b,d...z, and insufficient permissions for 'c', I have found it by elimination without any read permissions)

**What is the expected behavior?**
I would also like to get an 'Insufficient Permissions' error when no nodes are present.

**Comment by marktani** [comment]
As this is no bug, could you please create [a new feature request](https://github.com/graphcool/feature-requests)?

**Comment by kbrandwijk** [comment]
Done: https://github.com/graphcool/feature-requests/issues/314
