### ISSUE TITLE
createUser mutation returns an error although the user is created

### ISSUE THREAD

**Issue by bogdansoare** [graphcool/api-bugs#194]
**What is the current behavior?**
Creating a user with the mutation `createUser` from the Email-Password auth integration returns an error although the user is created

<img width="1145" alt="screen shot 2017-07-19 at 11 58 00" src="https://user-images.githubusercontent.com/2750170/28367115-3db458d6-6c98-11e7-9e76-2049674a6705.png">

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```graphql
type User implements Node {
  address: String
  application: Application @relation(name: "ApplicationOnUser")
  assets: [Asset!]! @relation(name: "UserOnAsset")
  availability: UserAvailability
  bankAccount: BankAccount @relation(name: "UserOnBankAccount")
  company: Company @relation(name: "UserOnCompany")
  createdAt: DateTime!
  currentTimezone: String
  description: String
  earnings: Earnings @relation(name: "EarningsOnUser")
  email: String @isUnique
  firstName: String
  googleDocNotesLink: String
  id: ID! @isUnique
  isAdmin: Boolean! @defaultValue(value: false)
  languages: [Language!]! @relation(name: "UserOnLanguage")
  lastName: String
  notifications: [Notification!]! @relation(name: "UserOnNotification")
  password: String
  phone: String
  profileFeaturedProjects: [ProfileFeaturedProject!]! @relation(name: "UserOnProfileFeaturedProject")
  profilePicture: String
  projectInvitations: [ProjectInvitation!]! @relation(name: "ProjectInvitationOnUser")
  projects: [Project!]! @relation(name: "UserOnProject")
  roles: [Role!]! @relation(name: "RoleOnUser")
  skills: [Skill!]! @relation(name: "UserOnSkill")
  slackId: String @isUnique
  socialMediaLinks: [SocialMediaLink!]! @relation(name: "UserOnSocialMediaLink")
  status: UserStatus! @defaultValue(value: REGISTERED)
  tier: Tier @relation(name: "UserOnTier")
  updatedAt: DateTime!
}
```

**If applicable, share the query, mutation or subscription for reproduction**
```graphql
mutation ($email: String!, $password: String!) {
  createUser(
    authProvider: {
      email: { email: $email, password: $password} 
    }
  ) {
    id
  }
}
```

**What is the expected behavior?**
Create a user without an error.

**Comment by marktani** [comment]
Thanks for taking the time to report this! As a note to myself, I'd like to first try if using this schema reproduces the problem already:

```graphql
type User implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  isAdmin: Boolean! @defaultValue(value: false)
  updatedAt: DateTime!
}
```

Also, the state of the auth providers might affect the reproduction.

**Comment by marktani** [comment]
![image](https://user-images.githubusercontent.com/1780597/28367304-b6cab7ea-6c90-11e7-97e5-91c5f0940822.png)

**Comment by marktani** [comment]
This behaviour arises when the following two conditions are met:

* an "authentication provider" is active
* a RP pipeline function for `createUser` is active

Therefore, two immediate approaches exist to combat it:

* disable the authentication provider and use custom authentication instead
* replace the RP function with a SSS function where applicable

Please reach out to me in Slack if you're experiencing this problem and I'll be able to further help you out. We will not change this behaviour as authentication providers will slowly be phased out in the future.
