### ISSUE TITLE
Schema extensions: query/mutation name not part of context

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#196]
**What is the current behavior?**
If I create a schema extension with more than one query, and use an external webhook, I have no way of knowing which query was fired.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
```graphql
type AdditionPayload {
  sum: Int!
}

extend type Query {
  sum(a: Int! b: Int!): AdditionPayload
  add(a: Int! b: Int!): AdditionPayload
}
```
The external webhook receives the following, for both queries:
```json
{"data":{"a":1,"b":2},"context":{"request":{"sourceIp":"aaa.bbb.ccc.ddd","headers":{},"httpMethod":"post"}
```
So I am unable to handle this properly.

**What is the expected behavior?**
Add the query/mutation name to the webhook request.

**Comment by marktani** [comment]
This is not a bug, but undefined behaviour: Schema Extensions are limited to one query/one mutation per function right now. I can see how this is useful when you want to use the same payload for multiple queries/mutations. Could you make this a FR instead?

**Comment by marktani** [comment]
Good point, I'll keep this thread posted with updates from our side.

**Comment by marktani** [comment]
Indeed, this was undesired behaviour. Only one query/mutation is supported per schema extension function right now. 🙂

**Comment by kbrandwijk** [comment]
Well, then the new issue is that combining a query and a mutation in a SE gives a nice valiadtion error, but combining with only queries, or only mutations, they are silently ignored.
Also, I will still create a FR for query/mutation name in context, because it is only partly related to this.
