### ISSUE TITLE
Disabling schema extension has no effect

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#197]
**What is the current behavior?**
If you disable a schema extension, the query/mutation/types are still available, and can still be executed.

**What is the expected behavior?**
Disabling the schema extension disables the query, mutation, and types.

**Comment by kbrandwijk** [comment]
Still the same behavior...

**Comment by marktani** [comment]
The deploy will be rolled out soon 🙂

**Comment by marktani** [comment]
Now! 😄
