### ISSUE TITLE
Inconsistent validation for schema extensions

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#200]
**What is the current behavior?**
If you create a query, and a mutation, in a single schema extension, you get a validation message: Schema Extension Error: Schema must not contain more than one type extension.

However, if you create multiple queries, or multiple mutations, the validation message is not shown, and the extra queries/mutations are silently ignored.

**What is the expected behavior?**
Both scenario's should give the same validation message.

**Comment by marktani** [comment]
Thanks a lot for reporting this! And looking forward to your FR as well :D

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/feature-requests/issues/326

**Comment by marktani** [comment]
This is now fixed 💚
