### ISSUE TITLE
SE functions can't return scalar lists

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#203]
**What is the current behavior?**

Returning `Json` or `[Json]` in a SE function results in an error message.

## Reproduction

Create a new SE function with this schema:

```graphql
type JsonPayload {
  json: Json,
  jsons: [Json]
}

extend type Query {
   jsonQuery(
      query: String,
  ): JsonPayload
}
```

Then, first, return only the `json` field of the payload:

```js
module.exports = function sum(event) {
  return { data: {
    json: JSON.stringify({a: 1})
  }};
}
```

This will result in this error message:

> "The value in the field 'json' is not a valid Json: '\"{\\\"a\\\":1}\"'"

If you instead return this `json` field in the payload:

```js
module.exports = function sum(event) {
  return { data: {
    jsons: JSON.stringify([{a: 1}, {a: 2}])
  }};
}
```

you get this error message:

> Returned Json Object does not match the GraphQL type: Expected Collection as JsArray, but got \"[{\\\"a\\\":1},{\\\"a\\\":2}]\"

**What is the expected behavior?**

The values are returned and no error message is thrown.

**Comment by kbrandwijk** [comment]
You shouldn't stringify. The result type is not `String`, it's `Json`. Without stringify, both cases work.

**Comment by kbrandwijk** [comment]
Can you make this issue more generic?
 
You get this error for returning a string instead of Json Array: 
`Expected Collection as JsArray, but got "[{\"a\":1},{\"a\":2}]"`

If you return an Integer instead of a String, you get:
`Expected String as JsString, but got 3`

In fact, the error message is already pretty user friendly... How would you improve it?

**Comment by marktani** [comment]
`JsArray` or `JsString` are no terms a developer should be exposed to, because they are implementation specific.

I still couldn't make my example functions to work, how does your version differ?

**Comment by kbrandwijk** [comment]
```
module.exports = function sum(event) {
  return { data: {
    json: {a: 1}
  }};
}

module.exports = function sum(event) {
  return { data: {
    jsons: [{a: 1}, {a: 2}]
  }};
}
```

**Comment by marktani** [comment]
```graphql
type JsonPayload {
  json: Json,
  jsons: [Json]
}

extend type Query {
   jsonQuery(
      query: String,
  ): JsonPayload
}
```

```js
module.exports = function sum(event) {
  return { data: {
    json: {a: 1},
  	jsons: [{a: 1}, {a: 2}]
  }};
}
```

```graphql
query {
  jsonQuery(query: "") {
    jsons
    json
  }
}
```

results in 

> Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: cj5i34qoq4d9j0198j2zl40m4

**Comment by kbrandwijk** [comment]
You're function is named sum...

**Comment by marktani** [comment]
Same for

```graphql
type JsonPayload {
  jsons: [Json]
}

extend type Query {
   jsonQuery(
      query: String,
  ): JsonPayload
}
```

```js
module.exports = function sum(event) {
  return { data: {
  	jsons: [{a: 1}, {a: 2}]
  }};
}
```

```graphql
query {
  jsonQuery(query: "") {
    jsons
  }
}
```

> Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: cj5i377zgg9wa0109blscozym

**Comment by marktani** [comment]
Your function is named sum as well. The export default function will be used, and the name in the SDL definition.

**Comment by marktani** [comment]
Even if using `jsonQuery` consistently, the same behaviour occurs:

```graphql
type JsonPayload {
  jsons: [Json]
}

extend type Query {
   jsonQuery(
      query: String,
  ): JsonPayload
}
```

```js
module.exports = function jsonQuery(event) {
  return { data: {
  	jsons: [{a: 1}, {a: 2}]
  }};
}
```

```graphql
query {
  jsonQuery(query: "a") {
    jsons
  }
}
```

> Whoops. Looks like an internal server error. Please contact us from the Console (https://console.graph.cool) or via email (support@graph.cool) and include your Request ID: cj5i39n737l2101505h2y2mzt

**Comment by kbrandwijk** [comment]
SDL:
```
type AdditionPayload {
  sum: Json
}

extend type Query {
  add(a: Int! b: Int): AdditionPayload
}
```

Function:
```
module.exports = function add(event) {
  return {data: {sum: { result: 3 } } }
}
```

Query:
```
{
  add(a: 1, b: 2) {
    sum
  }
}
```

Result:
```
{
  "data": {
    "add": {
      "sum": {
        "result": 3
      }
    }
  }
}
```

**Comment by marktani** [comment]
works for me 🤔

**Comment by marktani** [comment]
```graphql
type AdditionPayload {
  sum: [Json]
}

extend type Query {
  add(a: Int! b: Int): AdditionPayload
}
```

```js
module.exports = function add(event) {
  return {data: {sum: [{ result: 3 }] } }
}
```

doesn't work for me

**Comment by kbrandwijk** [comment]
If I create a normal Type with a JSON array field, I can't get a create mutation to work either...
```
type Test implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  test: [Json!]!
  updatedAt: DateTime!
}
```

```
mutation {
  createTest(test: [{a: 1}, {b: 2}]) { id }
}
```

`Argument 'test' expected type '[Json!]!' but got: [{a: 1}, {b: 2}]`

**Comment by marktani** [comment]
ah, you need to do `createTest(test: ["{a: 1}", "{b: 2}"]) { id }`

**Comment by kbrandwijk** [comment]
Data browser allows: `[{"b": 2} , {"a": 1} ]` (only quotes around the fields)

**Comment by kbrandwijk** [comment]
So we have: 
- Friendly error messages when wrong field type is returned from SE
- Returning JSON arrays does not work
- Inconsistency between playground and data browser for passing JSON array arguments

**Comment by kbrandwijk** [comment]
> ah, you need to do createTest(test: ["{a: 1}", "{b: 2}"]) { id }
This does not work

**Comment by marktani** [comment]
I'm sorry, I lied. You need to say `createTest(test: ["{\"a\": 1}", "{\"b\": 2}"]) { id }`, which is consistent as the data browser handles the escape.

This looks like it might be the cause for the other problems as well. I'll try to use "a" instead of a.

**Comment by kbrandwijk** [comment]
Tried that in the SE, couldn't get it to work...

**Comment by kbrandwijk** [comment]
`sum: ['{ "result": 3 }', '{ "otherResult": 4 }']`
`sum: ["{ \"result\": 3 }", "{ \"otherResult\": 4 }"]`
`sum: [{ result: 3 }, { otherResult: 4 }]`
`sum: [{ "result": 3 }, { "otherResult": 4 }]`
`sum: [{ "result": "3" }, { "otherResult": "4" }]`
`sum: ["{ result: 3 }", "{ otherResult: 4 }"]`

None of the above work...

**Comment by marktani** [comment]
Cool at this point I think we can stop brute forcing and just acknowledge it's a bug 😆

**Comment by kbrandwijk** [comment]
Last one:
```
var a = { result: 3}
var b = { otherResult: 4 }
return {data: { sum: [a, b] } }
```
Also doesn't work :smile:

**Comment by kbrandwijk** [comment]
By the way, I can't get an Array of any type from my SE. `[String]` also doesn't work, when trying to return:
`{"data":{"sum":["bla","blue"]}}}`

**Comment by marktani** [comment]
What's the error message then?

**Comment by kbrandwijk** [comment]
Updated https://github.com/graphcool/api-bugs/issues/203#issuecomment-317409012

**Comment by marktani** [comment]
scalar lists can now be returned as expected 🎉
