### ISSUE TITLE
Saving a specific SE function makes project inaccessible

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#205]
**What is the current behavior?**

Saving this SE SDL

```graphql
extend type Query {
  sum(a: Int! b: Int!): AdditionPayload
  add(a: Int! b: Int!): AdditionPayload
  dumdum(): Dummy
}

 type AdditionPayload {
   sum: Int!
 }
#
# extend type Mutation {
#   add(a: Int! b: Int!): AdditionPayload
#}
```

Makes the project inaccessible in the Console. Note the invalid use of `dumdum(): Dummy`.

**What is the expected behavior?**

Project is still accessible and SE function can be modified in the Console to fix this problem.

**Comment by kbrandwijk** [comment]
Additional information: `Dummy` is an existing 'regular' Type on the project.

**Comment by sorenbs** [comment]
This will now return a schema parsing error when creating or updating a schema extension function

**Comment by kbrandwijk** [comment]
I can confirm I can no longer pass an existing Type as parameter in a SE. I can still create a SE though with an existing Type as return type. Is this now supported?

**Comment by kbrandwijk** [comment]
Related to: https://github.com/graphcool/api-bugs/issues/216
