### ISSUE TITLE
Cannot store float with many decimals

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#208]
**What is the current behavior?**

Trying to store a float value with many (~15) digits behind the decimal point results in an error message.

**Reproduction**

```graphql
type A implements Node {
  f: Float
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

```graphql
mutation {
  createA(f: 1.23456789012345678) {
    id
  }
}
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "Argument 'f' expected type 'Float' but got: 1.23456789012345678. Reason: Float or Int value is too bit to fit in double (line 2, column 14):\n  createA(f: 1.23456789012345678) {\n             ^",
      "locations": [
        {
          "line": 2,
          "column": 14
        }
      ]
    }
  ]
}
```

**What is the expected behavior?**

The value should be stored, or a new error code should be returned.

**Comment by kbrandwijk** [comment]
This is according to specification. All numbers in Javascripts are 64-bit doubles according to IEEE 754. This means they have 15.95 (=16) decimal places.

This works:
```
mutation {
  createA(f: 0.1234567890123456) {
    id
  }
}
```
As the first `0` is ignored, you have 16 decimals left.
```
mutation {
  createA(f: 10.12345678901234) {
    id
  }
}
```
This also works, with a total of 16 decimals.

Sources: https://en.wikipedia.org/wiki/Double-precision_floating-point_format and https://en.wikipedia.org/wiki/IEEE_754

**Comment by Kiesco08** [comment]
@marktani @kbrandwijk Do you know what can be done on the client side to prevent this? On iOS for example, I fetch the user's longitude and latitude. I often end up with a Double that does not respect this specification. I've tried to manipulate the data different ways and did some research around this but I didn't come up with a clean way of getting around this. Any suggestions?

**Comment by piemonte** [comment]
hey @Kiesco08 i encountered this same exact issue! it was so frustrating.

it appears in iOS 11 changed the low-level behavior of floats compared to iOS 10, so floating points (even when truncated) will still change their approximate value in very very small fractions. my solution was to change our data model – submit locations as strings and then have a function on the server convert those string value into an IEEE-754 standardized Floats.  it rolled out smoothly and wasn't a breaking change for old clients.

**Comment by Kiesco08** [comment]
Thanks for sharing @piemonte! This seems to be the best solution for this situation

**Comment by piemonte** [comment]
props to @marktani too – wouldn't have done this without his guidance/help
