### ISSUE TITLE
SE query always uses first Type specified as return Type

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#216]
**What is the current behavior?**
If I specify any Type as return type for a SE, the SE always uses the first specified Type as return Type, regardless of the definition. Additionally, using an existing Type does not throw a validation error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
Both functions generate the same query.
1. Using an existing Type as return Type, the Payload Type is used instead:
```
type MyPayload2 { someField: Boolean }

extend type Query {
  add(a: Int! b: Int!): Post
}
```

2. Specifying more than one additional Type, the first one is always used:
```
type MyPayload2 { someField: Boolean }
type MyOtherPayload { someField: Boolean }

extend type Query {
  add(a: Int! b: Int!): MyOtherPayload
}
```

Both cases result in this query generated (from the Docs):
![image](https://user-images.githubusercontent.com/852069/28891485-f20e6cda-77ca-11e7-98b2-cd8f85d1362f.png)

**What is the expected behavior?**
The system should not create a different query than specified. If anything is wrong, throw a validation error instead.

**Comment by marktani** [comment]
This is now fixed 👍
