### ISSUE TITLE
Subscriptions do not fire on updates to relational fields

### ISSUE THREAD

**Issue by pcooney10** [graphcool/api-bugs#220]
**What is the current behavior?**
I am testing a subscription in the playground, and it does not recognize any changes to relational fields. For example, I have a `Place` type that has a `category` field. The `category` field is pulled from the `Category` type. When I make a change to the `category` field, nothing triggers in the subscription. The subscription only works for the `name` and `address` fields.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

````graphql
type Place implements Node {
  address: String
  category: Category @relation(name: "PlaceCategory")
  createdAt: DateTime!
  id: ID! @isUnique
  name: String!
  updatedAt: DateTime!
}
````

````graphql
type Category implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  name: String! @isUnique
  updatedAt: DateTime!
  places: [Place!]! @relation(name: "PlaceCategory")
}
````

**If applicable, share the query, mutation or subscription for reproduction**

````graphql
subscription {
  Place(
    filter: {
      mutation_in: [CREATED, UPDATED, DELETED]
    }
  ) {
    mutation
    node {
      id
      name
      address
      category {
        id
        name
      }
      createdAt
      updatedAt
    }
  }
}
````

**What is the expected behavior?**

As stated earlier, a change in the `category` field on the `Venue` type should trigger an update from the subscription.  I have tested this on other Types and other connected fields, and am experiencing the same error.

**Comment by pcooney10** [comment]
Also,  the `previousValues` argument does not recognize any of my relational fields, and kicks out an error when I try to include them.

````graphql
    subscription {
        Place(
          filter: {
            mutation_in: [CREATED, UPDATED, DELETED]
          }
        ) {
          mutation
          node {
            id
            name
            address
            category {
              id
              name
            }
            createdAt
            updatedAt
          }
        }
        updatedFields
        previousValues {
            name
            address
            category {
              id
              name
            }
        }
      }
````

I get the red squiggly lines when I try and type `category` in the playground, and when I press play I get the following error: `Cannot query field 'category' on type 'PlacePreviousValues'`.

**Comment by kbrandwijk** [comment]
https://github.com/graphcool/feature-requests/issues/146

**Comment by pcooney10** [comment]
@kbrandwijk dang i thought i searched everything ! But thank you for letting me know.

**Comment by marktani** [comment]
> I am testing a subscription in the playground, and it does not recognize any changes to relational fields

this is a current limitation. have a look here for workarounds: https://www.graph.cool/docs/reference/simple-api/relation-subscriptions-riegh2oogh/

> Also, the previousValues argument does not recognize any of my relational fields, and kicks out an error when I try to include them.

As mentioned [in the docs](https://www.graph.cool/docs/reference/simple-api/subscriptions-aip7oojeiv/), `previousValues` only contains *scalar* values and not relational ones.

As such, this is not a bug. Thanks for your report anyway! 🙏

**Comment by pcooney10** [comment]
Thank you @marktani, please see my comments here which be helpful:
https://github.com/graphcool/feature-requests/issues/107#issuecomment-320476909
