### ISSUE TITLE
Including a field called 'id' in an SE payload type causes internal server error

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#224]
**What is the current behavior?**
The returned data object structure is correct, however the SE still throws an internal server error (from the client/Playground only, the SE function logs shows a correct execution)

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
SDL:
```graphql
type GetWeatherByCityPayload {
  name: String
  dt: Float
  main: Json
  sys: Json
  wind: Json
  base: String
  id: Int
  coord: Json
  clouds: Json
  weather: [Json]
  visibility: Int
  cod: Int
}
``` 
Data returned from SE:
```json
{
  "coord": {
    "lon": 77.22,
    "lat": 28.63
  },
  "weather": [
    {
      "id": 701,
      "main": "Mist",
      "description": "mist",
      "icon": "50n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 29,
    "pressure": 1003,
    "humidity": 94,
    "temp_min": 29,
    "temp_max": 29
  },
  "visibility": 2500,
  "wind": {
    "speed": 2.32,
    "deg": 137.503
  },
  "clouds": {
    "all": 40
  },
  "dt": 1502222400,
  "sys": {
    "type": 1,
    "id": 7809,
    "message": 0.0029,
    "country": "IN",
    "sunrise": 1502151416,
    "sunset": 1502199359
  },
  "id": 1273840,
  "name": "Connaught Place",
  "cod": 200
}
```

However, if I rename the `id` field in the SDL and return data to `id2`, the function runs without error.

**What is the expected behavior?**
The SE should return the data, including the field named `id`, instead of throwing an internal server error.

**Comment by kbrandwijk** [comment]
Found something out, it's related to the id field. If I comment that one out, it works fine. Is it maybe that id is overridden somewhere, and that you can't return a field named id?

**Comment by marktani** [comment]
That sounds very likely :+1:

**Comment by kbrandwijk** [comment]
Yes, that's it. If I rename the field to `id2` in my SDL, and add `data.id2 = data.id` to my function, it runs without error.

**Comment by marktani** [comment]
For now, `id` is only allowed in a SE function if it is of type `ID` or `String` (or `!`).
