### ISSUE TITLE
specific schema changes are not registered using "apply changes"

### ISSUE THREAD

**Issue by moksahero** [graphcool/api-bugs#226]
**What is the current behavior?**
In Console
1. change relation name in console in two corresponding types
2. click "Preview Changes" to make sure there is no error and button turns "Apply Changes"
3. clicking "Apply Changes" turns the button back to "Preview Changes" nothing else happens

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**
change anything like field name or relation name and try to submit the change

**If applicable, share the query, mutation or subscription for reproduction**

**What is the expected behavior?**
3. clicking "Apply Changes" will make changes to the schema

**Comment by marktani** [comment]
Hey @moksahero, thanks for the report! Could you share your exact schema before and after the change? 🙂

**Comment by moksahero** [comment]
nothing happens the schema when "Apply Changes" is clicked so before and after schemata are exactly the same

**Comment by marktani** [comment]
Well, this bug only occurs for very specific changes. To be able to reproduce this bug, seeing what exact changes you are trying to apply is very helpful! :) So, the initial schema + the schema that you want to apply is what I mean.

**Comment by moksahero** [comment]
Before:
type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}

Changes I want to make:
type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}

**Comment by marktani** [comment]
Thanks 🙏  For reference, the change is `MessagesInChat` -> `MessagesOnChat`

**Comment by moksahero** [comment]
From:
type App implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
  name: String!
  teams: [Team!]! @relation(name: "TeamOnApp")
  stickers: [String!]
}

To:
type App implements Node {
  id: ID! @isUnique
  name: String!
  teams: [Team!]! @relation(name: "TeamOnApp")
  stickers: [String!]
  createdAt: DateTime!
  updatedAt: DateTime!
}

is also failing

**Comment by moksahero** [comment]
seems like any changes to this schema is not happening

**Comment by moksahero** [comment]
For reference, the change is MessagesInChat -> MessageOnChat
To be more precise but yes this is where change needs to happen

**Comment by marktani** [comment]
Hm that's strange, it should say `@isUnique` and not `@isunique` in your schema, maybe that's related?

**Comment by moksahero** [comment]
where did you spot @isunique?

**Comment by marktani** [comment]
here:

![image](https://user-images.githubusercontent.com/1780597/29131052-df02867e-7d2b-11e7-9d21-ee457d95cc1d.png)

**Comment by moksahero** [comment]
@isunique not sure how this happened. Let me paste again
Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

**Comment by moksahero** [comment]
ha commenting here with @ make everthing after lower case

**Comment by moksahero** [comment]
`Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}`

**Comment by moksahero** [comment]
`Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}`

**Comment by moksahero** [comment]
`
Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}
`

**Comment by moksahero** [comment]
I can't paste code here? that's crazy

**Comment by moksahero** [comment]
> Before:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessagesInChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessagesInChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

what I want:
type Chat implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "ChatsFromDashboardUser")
  channelUser: ChannelUser @relation(name: "ChatsFromChannelUser")
  messages: [Message!]! @relation(name: "MessageOnChat")
  createdAt: DateTime!
  updatedAt: DateTime!
}


type Message implements Node {
  id: ID! @isUnique
  dashboardUser: DashboardUser @relation(name: "MessagesFromDashboardUser")
  channelUser: ChannelUser @relation(name: "MessagesFromChannelUser")
  chat: Chat @relation(name: "MessageOnChat")
  text: String!
  createdAt: DateTime!
  updatedAt: DateTime!
}

**Comment by moksahero** [comment]
![screenshot from 2017-08-10 00-57-20](https://user-images.githubusercontent.com/700960/29131193-104e8cec-7d67-11e7-8f25-6755336ebeb1.png)

**Comment by marktani** [comment]
What's the change you mentioned in https://github.com/graphcool/api-bugs/issues/226#issuecomment-321297151? I can only see that you reordered the fields, is that correct?

**Comment by moksahero** [comment]
yes just pushing DateTime fields to the bottom. I can make this type of change too right?

**Comment by marktani** [comment]
No, this change is currently ignored, this explains the observed behaviour. There's already a feature request for this though: https://github.com/graphcool/feature-requests/issues/15

**Comment by moksahero** [comment]
so do you need any more info to fix this bug? Let me try to do it again. Thanks

**Comment by marktani** [comment]
No! To summarize:

* if the only change of a schema is renaming relations, it does not work
* if the only change of a schema is reordering fields, it does not work
