### ISSUE TITLE
Unsupported usage of console.log silently fails

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#232]
**What is the current behavior?**

If you use `console.log` like this:

```
console.log('returned data: ', data) 
```

in an inline function, the statement silently fails.

**What is the expected behavior?**

It should either behave as `console.log` in the browser (would be a feature request), or throw a helpful error message, that this is not supported.

**Comment by kbrandwijk** [comment]
I just tested the same in webtask.io, and it works there. Where does this restriction come from?

**Comment by marktani** [comment]
`console.log` is a custom implementation

**Comment by kbrandwijk** [comment]
In that case, I'm very much voting for 'behave as default console.log() in Auth0 webtasks'.
