### ISSUE TITLE
Passing null for optional values in RP functions doesn't work

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#233]
**What is the current behavior?**

Passing null for optional values in RP functions returns an error.

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

Create a new project with this schema:

```graphql
type A implements Node {
  id: ID! @isUnique
  optional: String
  createdAt: DateTime!
  updatedAt: DateTime!
}
```

Add this function to `TRANSFER_ARGUMENT` of `A is created`:

```js
// Click "EXAMPLE EVENT" to see whats in `event`
module.exports = function (event) {
  console.log(event.data)
  return {data: event.data}
}
```

**If applicable, share the query, mutation or subscription for reproduction**

Run this mutation:

```graphql
mutation a {
  createA(
    optional: null
  ) {
    id
  }
}
```

You'll receive this error message:

```json
{
  "data": {
    "createA": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createA"
      ],
      "code": 3036,
      "message": "The input value None was not valid for field optional of type String.",
      "requestId": "eu-west-1:simple:cj6ezicoqtuol01757jgih1xj"
    }
  ]
}
```

**What is the expected behavior?**

No error should be returned. It looks like the `optional` argument is being disregarded because it's `null`, but it should be applied.

**Comment by smiled0g** [comment]
I can confirm that this problem exists, and is causing us quite a bit of trouble.

Since our team relies on this a lot in our application, is there any progress on the fix?

**Comment by smiled0g** [comment]
Has this been fixed? @schickling

**Comment by schickling** [comment]
We're restructuring the issue tracking. This issue has been moved to: https://github.com/graphcool/graphcool/issues/431

**Comment by do4gr** [comment]
This closing was related to the restructuring. But the issue should also be fixed now @smiled0g . Can you please check and report back if it still persists?

**Comment by smiled0g** [comment]
It seems to be fixed for me. Thanks
