### ISSUE TITLE
Subscription misses mutations fired in quick succession

### ISSUE THREAD

**Issue by johanobergman** [graphcool/api-bugs#238]
**What is the current behavior?**
A subscription to a given type does not react to all mutations, if the mutations are fired in quick succession. A quick way to test this out is to create a new project with a test type, open the playground, start a subscription and in a new playground tab quickly fire multiple mutations. This behavior is not limited to the playground though.

**Example schema**
```graphql
type Foo implements Node {
  createdAt: DateTime!
  id: ID! @isUnique
  updatedAt: DateTime!
}
```

**Example mutation**
```graphql
mutation {
  createFoo {
    id
  }
}
```

**Example subscription**
```graphql
subscription {
  Foo {
    node {
      id
    }
  }
}
```

**What is the expected behavior?**
The subscription should record/respond to every mutation (preferably in the correct order), regardless of the time between mutations.

**Comment by marktani** [comment]
Hey @johanobergman, thanks a lot for reporting this problem! The only surefire way to verify that an expected payload has not been triggered is to look into the WS frames directly. At the moment, my assumption is that you're running into the same "display issue" as [described here](https://github.com/graphcool/console/issues/799). Could you please check whether or not this is the case?

Thanks 🙏

**Comment by johanobergman** [comment]
Yep, my bad, that's exactly what's happening! Even in my own app, the websocket receives the data but some results are simply ignored. I'm using apollo with the `subscriptions-transport-ws` client, maybe that's where the issue lies.

**Comment by marktani** [comment]
Gotcha! No worries this has caught me several times before as well 😄 
I guess a minimum non working example in a new issue for https://github.com/apollographql/subscriptions-transport-ws would be the best to help identifying the problems here. Feel free to create an example Graphcool project for that.

Closing this, let us know if you find out more!
