### ISSUE TITLE
Server Side Subscription dropping invocations (suspected parallelism issue)

### ISSUE THREAD

**Issue by mattfysh** [graphcool/api-bugs#243]
**What is the current behavior?**

An SSS Function has dropped an invocation when 3 applicable mutations occurred within quick succession of one another. The SSS Function was invoked only twice.

A similar SSS Function which also triggers when the same object type is updated successfully triggered three times.

The average duration for the Function which dropped an invocation is ~2000ms
And the average duration for the Function which was successfully invoked all 3 times is ~500ms

**Please share the relevant part of your GraphQL schema and all functions, permissions or other project settings for easier reproduction**

This does not appear to be a project-related issue.

**If applicable, share the query, mutation or subscription for reproduction**

For the SSS Function that only triggered twice:

```
subscription {
  MyType(filter: {
    mutation_in: [UPDATED]
    node:{
      status:NEWVALUE
    }
  }) {
    node {
      id
    }
  }
}
```

For the SSS Function that triggered three times:

```
subscription {
  MyType(filter: {
    mutation_in: [CREATED, UPDATED, DELETED]
  }) {
    node {
      id
    }
  }
}
```

**What is the expected behavior?**

The SSS Function should have been invoked once per mutation

**Comment by marktani** [comment]
Thanks for the bug report! Can you show the according mutation?

**Comment by mattfysh** [comment]
```
mutation UpdateStatus($id: ID!) {
    updateMyType(id: $id, status: NEWVALUE) {
      id
    }
  }
```
