### ISSUE TITLE
Passing 'undefined' to a filter causes unexpected results. 

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/api-bugs#244]
Given is a simple model of Posts and Users, with a 1:n relationship between Users and Posts.

Consider a basic query, like like the following: 

```
query test($userId: ID) {
  allPosts(filter: {user: {id: $userId}}) {
    id
  }
}
```

When passing `null` for the variable (e.g. setting the payload to `{ userId: null }`, an empty result set is returned, as expected. 

However, when passing `undefined` for the variable (by setting the payload to `{ userId: undefined }`), all existing posts are returned. 

Expected behaviour: 
* Raise an error, as `undefined` [is not valid JSON](https://stackoverflow.com/questions/13796751/json-undefined-value-type). 
* Or treat undefined and null as the same

**Comment by kbrandwijk** [comment]
How are you passing in undefined?

**Comment by ejoebstl** [comment]
Basically setting the body of the HTTP request like this: 

```
{ query: (query from above), variables: { userId: undefined } }
```

It's something that can happen quite easily when programming in JavaScript.

**Comment by kbrandwijk** [comment]
Like I said, if it's `undefined`, it's ignored, if it's `null`, a `null` value is used in the query.

**Comment by ejoebstl** [comment]
Good to know. 

That makes sense.
