### ISSUE TITLE
Collaborator can delete someone else's last project

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/api-bugs#246]
**What is the current behavior?**
A collaborator can delete a project.

**What is the expected behavior?**
A collaborator should not be able to delete a project.

Related: a collaborator can delete someone else's last project, which you cannot do yourself. If you decide not to fix the main issue, then please create a seperate issue for this one...

**Comment by marktani** [comment]
Thanks! The general case is a feature request and will be covered once we introduce access control configuration for collaborators: https://github.com/graphcool/feature-requests/issues/94

That a collaborator can delete the last project of someone else is unintended and should be changed.
