### ISSUE TITLE
File mutation callbacks not working

### ISSUE THREAD

**Issue by adrianocola** [graphcool/api-bugs#28]
Mutation callbacks for Files are not called. Tested with create and delete mutations.

**Comment by marktani** [comment]
Thanks for the report. A possible workaround is to create a relation between `File` and another model and create the other model whenever a new file is uploaded. Then the mutation callback on the other model can be used.

**Comment by marktani** [comment]
I migrated this to a feature request: https://github.com/graphcool/feature-requests/issues/256.
