### ISSUE TITLE
A search in a model fails with an apostrophe

### ISSUE THREAD

**Issue by arthur31416** [graphcool/api-bugs#35]
Any search with an apostrophe will raise this error:
```Cannot read property 'viewer' of undefined```

**Comment by marktani** [comment]
Can you clarify what you mean with a search with an apostrophe? Are you using a specific GraphQL client or are you using the Playground?

**Comment by arthur31416** [comment]
I got this issue in the console. It looks like this:

![sc](https://cloud.githubusercontent.com/assets/12168491/24911368/f70e98f8-1eca-11e7-8337-a1fad430ed03.png)

**Comment by marktani** [comment]
Ah I see! Thanks for the report, I migrated the issue to the Console tracker: https://github.com/graphcool/console/issues/823
