### ISSUE TITLE
GraphQL error: Unknown argument 'deleted' on field 'removeFromPostsOnComments'

### ISSUE THREAD

**Issue by TheoMer** [graphcool/api-bugs#36]
So, I have a one to many relationship from Posts to comments:

```
    type Comments {
      createdAt: DateTime!
      deleted: Boolean
      id: ID!
      posts: Posts @relation(name: "PostsOnComments")
      text: String!
      updatedAt: DateTime!
      user: String!
    }

    type Posts {
      caption: String!
      comments: [Comments!]! @relation(name: "PostsOnComments")
      createdAt: DateTime!
      displaysrc: String!
      id: ID!
      likes: Int
      updatedAt: DateTime!
    }

```

and wish to run a mutation, which as well as deleting the connection between a post and a comment, attempts to update the field 'deleted, on Comments, to true:

```
    mutation removeComment ($id: ID!, $cid: ID!, $stateB: Boolean) {
      removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid, deleted: $stateB){
        postsPosts {
          __typename
          id
          comments {
            __typename
            id
            text
            user
            deleted
            posts {
              __typename
              id
            }
          }
        }
      }
    }
      
    Query Variables

    {
      "id": "cj0qkl04vep8k0177tky596og",
      "cid": "cj1de905k8ya201934l84c3id"
    }
```

But when I run the mutation I get the following error message:

```
      "data": null,
      "errors": [
        {
          "message": "Unknown argument 'deleted' on field 'removeFromPostsOnComments' of type 'Mutation'. (line 2, column 77):\n    removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid, deleted: $stateB){\n                                                                            ^",
          "locations": [
            {
              "line": 2,
              "column": 77
            }
          ]
        }
      ]
    }
```

As was explained to me [here][1], only the link between Posts and comments is deleted, not the actual 'Comment' record itself. So my thinking is, as the record is not deleted, why can I not update the 'deleted' field? 

I wish to do this so that it triggers a subscription, which is monitoring the [updated][2] field 'deleted'.

As can be seen in the image, 'deleted' is definitely included in 'Comments' of my GraphCool schema:

[![enter image description here][3]][3]

  [1]: http://stackoverflow.com/questions/43242475/graphql-subscription-not-firing-when-mutation-run
  [2]: https://www.graph.cool/docs/reference/simple-api/subscribing-to-updated-nodes-ohmeta3pi4/#subscribe-to-updated-fields
  [3]: https://i.stack.imgur.com/obo3Z.jpg

**Comment by marktani** [comment]
The mutation to remove a connection for a specific relation cannot be used to also update a value of one of the nodes. You need to use the `updateComment` mutation for that, like this:

```graphql
mutation removeComment ($id: ID!, $cid: ID!, $stateB: Boolean) {
  removeFromPostsOnComments (postsPostsId: $id, commentsCommentsId: $cid) {
    postsPosts {
      __typename
      id
      comments {
        __typename
        id
        text
        user
        deleted
        posts {
          __typename
          id
        }
      }
    }
  }

  updateComment(id: $id, deleted: $stateB) {
    id
  }
}
```

In general, I would recommend testing out mutations in the Playground right in the console first, where you get autocompletion and a quicker feedback loop. Hope that helps! :slightly_smiling_face:
