### ISSUE TITLE
Relay API hasNextPage returns false incorrectly

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#46]
```graphql
{
  viewer {
    allProducts(first: 2) {
      count
      pageInfo {
        hasNextPage
      }
      edges {
        node {
          id
        }
      }
    }
  }
}
```

returns

```json
{
  "data": {
    "viewer": {
      "allProducts": {
        "count": 5,
        "pageInfo": {
          "hasNextPage": false
        },
        "edges": [
          {
            "node": {
              "id": "cj1hqd55avzss01978uescpb1"
            }
          },
          {
            "node": {
              "id": "cj1hqe5h8vlec0145teg9enf5"
            }
          }
        ]
      }
    }
  }
}
```

As per the [Relay cursor specification](https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields), `hasNextPage` should return `true` in this case.

**Comment by rtymchyk** [comment]
The full complete `pageInfo` object is actually broken:
```javascript
"pageInfo": {
  "hasNextPage": false,
  "hasPreviousPage": false,
  "endCursor": null,
  "startCursor": null
},
```
This can be reproduced with any connection.

**Comment by nosykretts** [comment]
Please fix this. Relay APi without working relay cursor spesification is not Relay API.

**Comment by rtymchyk** [comment]
This has been open for a month, are there any upgrades? Agree with @nosykretts. Not having working connections is making the APIs unusable

**Comment by nosykretts** [comment]
1.5 month still no progress 😢

**Comment by marktani** [comment]
Thanks @rtymchyk and @nosykretts, we're already looking into this 🙂 This will be fixed as part of a bigger refactor for the changes that come with Relay Modern.

**Comment by jhalborg** [comment]
@marktani - Any release ETA for that refactor? :-)

**Comment by hallister** [comment]
I'm a little surprised this has gone nearly 2 months now. This isn't something you bundle with a refactor, this is a major bug that makes Relay pagination non-working. Outside of play projects, graph.cool is unusable for Relay.

**Comment by kbrandwijk** [comment]
Funny, that's exactly how I feel about Relay. It's nice for play projects, or if you control every aspect in the client -> server chain, like Facebook, but out in the real world, it's unusable.

**Comment by hallister** [comment]
I mean you nailed it, but frankly that's on the SaaS providers that only implement token Relay support or, you know, list a critical bug as a refactor. I used Scaphold for a long time, but it took them months just to add the `viewer` into responses for a mutation, so Relay would never know when data was added/remove.

At the end of the day it's use-case dependent. If you need offset/skip based pagination, you shouldn't be using Relay.

**Comment by marktani** [comment]
Thanks for sharing your thoughts @hallister! Indeed, we're already working on this separately before tackling the Relay Modern refactor. I'll keep this thread posted with further updates 🙂

**Comment by marktani** [comment]
Thanks everyone for your feedback here 🙏  the `pageInfo` works now correctly in all cases.
