### ISSUE TITLE
Race condition with read permissions & node connections

### ISSUE THREAD

**Issue by grncdr** [graphcool/api-bugs#49]
Sorry for the long post, I attempted to separate out a minimal reproduction from the app I'm working on. I am not sure I've diagnosed this correctly, but here's what I've observed.

## Schema

I have a type `Test` with a relation named `owner` to `User`. Each user can own multiple tests. `Test` also contains an arbitrary other field (I called it `someNumber`).

### User

Everyone has permission to read `User.id`.
Authenticated users have permission to read their own full `User` node with the following permission query:

```graphql
query ($user_id: ID!, $node_id: ID!) {
  SomeUserExists(filter: {
    AND: [{
      id: $user_id
    }, {
      id: $node_id
    }]
  })
}
```

### Test

Authenticated users have permission to create `Test` nodes (whole type).

Authenticated users have permission to read `Test` nodes (whole type) that they own, using the following permission query:

```graphql
query ($node_id: ID!, $user_id: ID!) {
  SomeTestExists(
    filter: {
      AND: [{
        id: $node_id
      }, {
        owner: {
          id: $user_id
        }
      }]
    }
  )
}
```

### UsersTests relation

```graphql
query ($ownTestsTest_id: ID!, $ownerUser_id: ID!, $user_id: ID!) {
  SomeTestExists(filter: {
    AND: [{
      id: $ownTestsTest_id
    }, {
      owner: null
    }]
  })
  
  SomeUserExists(filter: {
    AND: [{
      id: $ownerUser_id
    }, {
      id:$user_id
    }]
  })
}
```

## Triggering the bug

Given the above set up, execute the following mutation with the `$ownerId` variable set to the ID of the current user (e.g. use the "Select User" option in the playground):

```graphql
mutation($ownerId: ID!){
  createTest(ownerId: $ownerId){
    id
    someNumber
  }
}
```

### Expected behavior

The new `Test` is created and all of relevant fields are returned.

### Observed behavior

The new `Test` node *is* created reliably, but I receive permission errors about not being able to read `["createTest", "someNumber"]`. These errors are not 100% reliable, but it seems to happen roughly 80% of the time.

I've created a small test project that demonstrates the issue. If somebody from graph.cool would like to check it out I'm happy to invite you as a collaborator.

**Comment by marktani** [comment]
Hey @grncdr, thanks for the detailed write up 👍 I'll reach out to you in Slack.

**Comment by sorenbs** [comment]
Thank you so much for this super detailed bug report - it really does make a difference!

The issue should be resolved now. Can you please verify before I close this issue?

**Comment by grncdr** [comment]
It seems resolved in my test project. I will recreate the permissions queries in my real app and reply here again.

**Comment by grncdr** [comment]
Yeah, so far so good, I haven't run into any strange issues. I think this is safe to close 👍

**Comment by marktani** [comment]
Thanks so much Stephen! 🙌
