### ISSUE TITLE
SSS sometimes don't send the updated data after an UPDATE

### ISSUE THREAD

**Issue by adrianocola** [graphcool/api-bugs#61]
I’m using a SSS with a webhook but when I do a mutation from my application my webhook receives the data without my modifications. If I change the same item in the console my webhook receives the data with the changes.

This is my Subscription:
```graphql
subscription {
  Reviewer(filter: {
    mutation_in: [UPDATED]
    updatedFields_contains: "responded"
  }) {
    updatedFields
    node {
      id
      responded
    }
  }
}
```

I'm only changing the field `responded` in both cases.

UPDATE: sometimes the issue happens even when using the console.

**Comment by marktani** [comment]
Can you please try again? :)

**Comment by adrianocola** [comment]
Working now! Thank you @marktani!
