### ISSUE TITLE
problem creating new schema when it contains enums

### ISSUE THREAD

**Issue by stlbucket** [graphcool/api-bugs#62]
steps to repro:

- create new project via UI.   
- add enums.

with cli:
- graphcool init --copy [projectID]
- change filename from clone-project.graphcool to project.graphcool
- graphcool push

![image](https://cloud.githubusercontent.com/assets/2467892/26270192/0e72403c-3cbf-11e7-80ab-c2145de7f4d9.png)

**Comment by stlbucket** [comment]
another related issue:

if you subsequently delete an enum through the UI, it still shows up via graphcool pull

**Comment by stlbucket** [comment]
steps to build out (copy) schema that seem to be least work right now:
- clone existing schema to graphcool.project
- init a new, blank project
- remove all enums and enum fields from graphcool.project
- graphcool push new schema
- manually add enums and enum fields to project

**Comment by marktani** [comment]
This has been fixed 🙂
