### ISSUE TITLE
Request pipeline internal server error

### ISSUE THREAD

**Issue by joarwilk** [graphcool/api-bugs#64]
Request ID: cj301h7rvk6ov015345y6epca

Request-Pipeline Step: PRE_WRITE (Create mutation)
Function type: Webhook

My lambda code is never invoked, and the logs (as shown in the function editor) are empty. Looks like the error is early in the stack.

Everything works when using the function test runner. It only fails when the event is spawned by an actual mutation.

**Comment by marktani** [comment]
@joarwilk can you confirm that the function works when you use the "top-level" create mutation, and it does not work when using the nested mutation?

**Comment by joarwilk** [comment]
@marktani Yep, confirmed.

**Comment by marktani** [comment]
This is now fixed 🙂
