### ISSUE TITLE
Error in the deleteFile mutation

### ISSUE THREAD

**Issue by vmatacale** [graphcool/api-bugs#70]
I'm getting an error from the deleteFile mutation

My query (apollo client) 
{"query":"mutation deleteFile($id: ID!) {\n deleteFile(id: $id) {\n id: id\n __typename\n }\n}\n","variables":{"id":"cj2z2cndk000401288jhnzluq"},"operationName":"deleteFile"}

The response
{"data":{"deleteFile":null},"errors":[{"message":"Whoops. Looks like an internal server error. Please contact us in Slack (https://slack.graph.cool) and send us your Request ID: cj2z2d2g586fs01222pfthzq4","requestId":"cj2z2d2g586fs01222pfthzq4","path":["deleteFile"],"locations":[{"line":2,"column":3}]}]}

**Comment by jhalborg** [comment]
https://github.com/graphcool/api-bugs/issues/76 linked issue

**Comment by marktani** [comment]
This should now be fixed 🙂
