### ISSUE TITLE
Deleting a field that is used in a function returns a very generic error

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#80]
> [{"data":{"updateReview":null},"errors":[{"message":"Query does not pass validation. Violations:\n\nCannot query field 'started' on type 'Review'. Did you mean 'status' or 'startDate'? (line 10, column 7):\n      started\n      ^","path":["updateReview"],"locations":[{"line":2,"column":3}]}]}]

it's not clear that the function is the problem. Could be also a permission query, Algolia index...

**Comment by marktani** [comment]
related to #92.

**Comment by schickling** [comment]
➤ Nilan Marktanner commented:

migrate this to a FR.

**Comment by marktani** [comment]
I migrated this to [this FR](https://github.com/graphcool/feature-requests/issues/252).
