### ISSUE TITLE
CORS error when executing function in Test Run

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#83]
https://github.com/graphcool/console/issues/1033

**Comment by marktani** [comment]
Hey @pbassut, it looks like you are not resolving a promise correctly, could that be the case?

**Comment by marktani** [comment]
Here's a working example: https://github.com/graphcool-examples/functions/blob/master/stripe-coupons/check-coupon.js

If I change `resolve(event)` to `return event` I also get the error you get, because the function times out 🙂

**Comment by pbassut** [comment]
@marktani Sorry I missed your response.
I don't see any promise not being resolved in my script.
Every time there's a resolve I use it instead of returning.

**Comment by marktani** [comment]
Yea your function seems to have problems with the file upload which is a separate issue.

**Comment by marktani** [comment]
I talked to @pbassut and he could resolve this problem.
