### ISSUE TITLE
Logic with Multiple filters in Relations Permission Query

### ISSUE THREAD

**Issue by guilcorp** [graphcool/api-bugs#84]
The logic between the 2 filters below should be an AND but it act like an OR.

```graphql
query ($engageInPact_id: ID!, $user_id: ID!, $participantsUser_id: ID!) {
  SomeUserExists(filter:{
    AND: [
      {id:$user_id}
      {id:$participantsUser_id}
    ]
  })
  SomePactExists(filter: {
    AND: [
      {id:$engageInPact_id}
      {OR:[
            {public:true}
            {viewerUsers_some: {id: $user_id} }
            {viewerGroups_some:{ users_some: {id: $user_id}} }
        ]}
    ]
  })
}
```

**Comment by marktani** [comment]
Thanks for bringing this up @guilcorp, we will fix this behaviour soon and reached out to everyone who uses two or more `SomeXExists` fields in a PQ to allow for adjustment to avoid a breaking change. I'll close this ticket as soon as we corrected the current behaviour to follow the specified behaviour.

**Comment by marktani** [comment]
The behaviour of multiple root-queries in a permission has now been adjusted as described [in the documentation](https://www.graph.cool/docs/reference/auth/permission-queries-iox3aqu0ee/#the-execution-and-evaluation-of-permission-queries). They are combined using `AND`, so both queries need to return `true` to make the permission accept a certain mutation or query.
