### ISSUE TITLE
Can't make optional relational field required

### ISSUE THREAD

**Issue by delgermurun** [graphcool/api-bugs#90]
Message type has "user" relation field with User type. It is optional and I added few instances via a console.

I can't make this field required. It gives "_**The relation field `user` cannot be made required, because there are already instances of the enclosing type that violate this constraint.**_" this error. All "user" fields have value.

**Comment by marktani** [comment]
This works using the UI, but not using the schema editor.

**Comment by marktani** [comment]
This is now fixed also in the schema editor 🙂
