### ISSUE TITLE
Functions on mutation fail when nested input objects are part of the mutation

### ISSUE THREAD

**Issue by marktani** [graphcool/api-bugs#94]
Executing this mutation:
```graphql
mutation placeOrder(
$userId: ID!, $refillAt: Int!, $totalCost: Float!, $taxCost: Float!, $shipCost: Float!, $balance: Float!, $shopItems: [OrdershopItemsShopItem!], $bundleShopItems: [OrderbundleShopItemsBundleShopItem!],
$deliveryDate: DateTime!, $addressId: ID!, $cardDetailId: ID!) {
  createOrder(userId: $userId, refillAt: $refillAt, totalCost: $totalCost, taxCost: $taxCost, shipCost: 
                       $shipCost, balance: $balance, shopItems: $shopItems, bundleShopItems: 
                       $bundleShopItems, deliveryDate: $deliveryDate, shipAddressId: $addressId, 
                       cardDetailId: $cardDetailId) {
    id
    __typename
  }
}
```

when a function is defined for `TRANSFORM_ARGUMENT` on `Order is created` results in an internal server error.

**Comment by marktani** [comment]
@barbatus, can you confirm that the mutation works fine when you leave out the arguments `shopItems` and `bundleShopItems`?

**Comment by barbatus** [comment]
@marktani actually no it doesn't. It throws same exception even when I post:
`mutation placeOrder($userId: ID!, $refillAt: Int!, $totalCost: Float!, $taxCost: Float!, $shipCost: Float!, $balance: Float!, $deliveryDate: DateTime!, $addressId: ID!, $cardDetailId: ID!) {↵  createOrder(userId: $userId, refillAt: $refillAt, totalCost: $totalCost, taxCost: $taxCost, shipCost: $shipCost, balance: $balance, deliveryDate: $deliveryDate, shipAddressId: $addressId, cardDetailId: $cardDetailId) { id }`

**Comment by marktani** [comment]
Oh ok. Can you post a request id of a failing request?

**Comment by barbatus** [comment]
@marktani cj3oglxt14hzp0175ojlew57v

**Comment by marktani** [comment]
It looks like the mutation related to this request id indeed included the `shopItems` and `bundle ShopItems` arguments, can you send a request id without those arguments?

**Comment by barbatus** [comment]
@marktani here is cj3ohg6ohk7qa0128d1ou8d8t but i don't understand why though it's my often state when i work with graphcool

**Comment by marktani** [comment]
This is Interesting, it seems to be two separate bugs. Could you, please, try both mutations again but this time disable the function completely. Do both mutations work as expected?

Thanks for bearing with me! 🙏

**Comment by barbatus** [comment]
@marktani yes it's a real mutation used in the prod. If i turn on transform pipeline function on the Order table it stops working (incl. the one w/o `shopItems `)

**Comment by marktani** [comment]
I see! You helped me gather enough information to reproduce this internally, thanks 🙏  I'll update this issue once we fixed this problem 🙂

**Comment by marktani** [comment]
The other problem you're facing is documented and tracked in #111.

**Comment by marktani** [comment]
As a summary: 

These are two separate issues when identity function for `TRANSFORM_ARGUMENT` on top-level mutation is active:

* mutation fails when nested arguments are included (see this: https://app.bugsnag.com/graphcool/prod/errors/5922c4e8f5539000186122cd?filters%5Bevent.since%5D%5B%5D=1d)
* mutation fails when `DateTime` argument is included (see this: https://app.bugsnag.com/graphcool/prod/errors/58bd7baed75411972b9611d1?filters%5Bevent.since%5D%5B%5D=2017-06-08T02%3A17%3A42.478Z&filters%5Bevent.before%5D%5B%5D=2017-06-08T23%3A54%3A13.353Z&event_id=593956aab87ded0018c2139e)

Both these errors **don't** occur when the function is disabled.

**Comment by barbatus** [comment]
I guess it'll take another two months to fix these issues as it was with functions for nested mutations. It's really ridiculous since you released this feature certainly not testing it at all. These cases are so obvious.

**Comment by marktani** [comment]
A [very similar bug](https://github.com/graphcool/api-bugs/issues/175) has been fixed. Can you check if that issue still occurs, please?

**Comment by marktani** [comment]
I'll consider this issue fixed. If it still occurs, please create a new one. Thanks for your help 🙏
